name: my First workflow

on: push

jobs:
    first_job:
        runs-on: Ubuntu-latest
        steps:
            - name: checkout-repo
              uses: actions/checkout@v6

            - name: list and reads file message
              run: |
                   echo "hello"
                   ls -ltr
                   cat README.md

            - name : generate ASCII artwork
              run : cowsay -f dragon "Run for cover ,I am a DRAGON ...RAWR" >> dragon.txt
                

           # - name: list files
            #  run: ls

            #- name: Read files
             # run: cat README.md


